[[session]]
name = "Dotfiles"
path = "~/dotfiles/"

[[session]]
name = "neovim config"
path = "~/dotfiles/.config/nvim"
startup_command = "vim"

[[session]]
name = "wezterm config"
path = "~/dotfiles/.config/wezterm"
startup_command = "vim wezterm.lua"

[[session]]
name = "Notes"
path = "~/EDF/private/notes"
startup_command = "vim"
